services:
  nginx-proxy:
    container_name: nginx-proxy
    image: nginxproxy/nginx-proxy:${NGINX_PROXY_TAG}
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    tty: true
    volumes:
      - ./nginx-proxy/nginx.conf:${NGINX_CONF}
      - ./nginx-proxy/cors.conf:${NGINX_PROXY_CORS_CONF}
      - html:${NGINX_HTML}
      - vhost:${NGINX_VHOST}
      - certs:${NGINX_CERTS}:ro
      - ${DOCKER_SOCK}:${TEMP_DOCKER_SOCK}:ro
    environment:
      - TRUST_DOWNSTREAM_PROXY
      - CORS_ALLOWED_DOMAIN
    networks:
      - internal
    # profiles: [$NGINX_PROXY_PROFILES]
  
  letsencrypt:
    container_name: letsencrypt
    image: nginxproxy/acme-companion:${ACME_COMPANION_TAG}
    restart: unless-stopped
    depends_on:
      - nginx-proxy
    volumes_from:
      - nginx-proxy:rw
    volumes:
      - certs:${NGINX_CERTS}:rw
      - acme:${NGINX_ACME}
      - ${DOCKER_SOCK}:${DOCKER_SOCK}:ro
    environment:
      - ACME_CA_URI
      - CERTS_UPDATE_INTERVAL
      - DEFAULT_EMAIL
    networks:
      - internal
    # profiles: [$ACME_COMPANION_PROFILES]

  postgres:
    container_name: postgres
    restart: unless-stopped
    build: 
      context: ./
      dockerfile: ./postgres/Dockerfile
      args:
        - POSTGRES_TAG
    tty: true
    volumes:
      - pg-data:${PGDATA}
      # - ./postgres/entrypoint.sh:/docker-entrypoint-initdb.d/entrypoint.sh
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - PGDATA
      - DB_USER
      - DB_TEMPLATE
      - UNACCENT_TEMPLATE
      - PGADMING_DB_NAME
      - PGADMING_DB_USER
      - PGADMIN_DB_PASSWORD
    networks:
      - internal
    ports:
      - 5432:5432
    # profiles: [$POSTGRES_PROFILES]

volumes:
  html:
  vhost:
  certs:
  acme:
  pg-data:

networks:
  internal:
    driver: bridge
    name: internal
