# Allows the usage of $CORS_ALLOWED_DOMAIN
upstream odoo {
    server odoo:8069;
}
upstream odoochat {
    server odoo:8072;
}

map $http_x_cors_allowed_domain $CORS_ALLOWED_DOMAIN {
    default "*";
}

server {
    client_max_body_size 4096m;

    proxy_connect_timeout 900;
    proxy_send_timeout 900;
    proxy_read_timeout 900;
    send_timeout 900;

    listen [::]:80;
    listen 80;

    server_name $VIRTUAL_HOST;

    location ~ /.well-known/acme-challenge {
        allow all;
        root /var/www/html;
    }

    location / {
        proxy_pass http://odoo;
        proxy_redirect off;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Real-IP  $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # proxy_cookie_flags session_id samesite=lax secure;

        # Add CORS headers
        add_header 'Access-Control-Allow-Origin' $CORS_ALLOWED_DOMAIN;
        add_header 'Access-Control-Allow-Credentials' 'true';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
        add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
        add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range';
        if ($request_method = 'OPTIONS') {
            return 204;
        }
    }

    location /websocket {
        proxy_pass http://odoochat;
        proxy_redirect off;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # proxy_cookie_flags session_id samesite=lax secure;
    }
    
    location /web/database/selector {
        rewrite ^/web/database/selector$ http://$host/web?db=$host permanent;
    }

    # common gzip
    gzip_types text/css text/scss text/plain text/xml application/xml application/json application/javascript;
    gzip on;
}
